export const LEARNING_PHASES = [
    {
        id: 1,
        title: 'Fundamentos',
        subtitle: 'Seguridad, precisión y herramientas',
        duration: '2-3 meses',
        color: '#8B5E3C',
        icon: '🪚',
        objectives: [
            'Usar las herramientas con seguridad total y confianza',
            'Realizar cortes rectos y precisos de forma consistente',
            'Entender la madera: vetas, humedad, tipos de tableros',
            'Leer y hacer planos simples con medidas',
        ],
        skills: [
            'Medición y marcado preciso (escuadra, metro, gramil)',
            'Cortes rectos con sierra de banco e ingletadora',
            'Calado de formas curvas básicas',
            'Lijado manual: progresión de granos',
            'Seguridad: EPP, guardas, orden del taller',
        ],
        exercises: [
            'Cortar 20 piezas de 30cm exactamente iguales → medir variación',
            'Construir una caja simple encolada (sin herrajes)',
            'Hacer un banco de apoyo pequeño para tu taller',
            'Probar 3 tipos de madera distintos y registrar diferencias',
        ],
        resources: [
            'Videos: técnica de medición y marcado preciso',
            'Videos: "El Carpintero del Desierto" — episodios de inicio',
            'Videos: uso seguro de sierra de banco',
            'Libro referencia: "The Complete Manual of Woodworking"',
        ],
    },
    {
        id: 2,
        title: 'Ensambles y Estructuras',
        subtitle: 'Uniones resistentes y sólidas',
        duration: '3-4 meses',
        color: '#6B4423',
        icon: '🔧',
        objectives: [
            'Dominar los ensambles fundamentales de carpintería',
            'Construir estructuras que no se tambaleen ni suelten',
            'Entender cuándo usar cola, tornillos, espigas o clavijas',
            'Leer y ajustar tolerancias de ajuste',
        ],
        skills: [
            'Espiga y mortaja (básica con router)',
            'Cola de Milano (intro)',
            'Ranura y lengüeta',
            'Ensambles atornillados reforzados con tarugos',
            'Uso del router de mano para canales y perfiles',
            'Aplomado y escuadrado de muebles',
        ],
        exercises: [
            'Hacer 5 tipos de uniones diferentes en madera de práctica',
            'Construir un taburete/banco con espigas y cola',
            'Hacer una pequeña repisa con ranura y lengüeta',
            'Proyecto mesa auxiliar simple (tu primer mueble funcional)',
        ],
        resources: [
            'Videos: técnicas de ensamble — espiga y mortaja',
            'Videos: uso del router para ensambles',
            'Canales: Fine Woodworking, Paul Sellers (YouTube)',
        ],
    },
    {
        id: 3,
        title: 'Acabados Profesionales',
        subtitle: 'Detalles finos y superficie perfecta',
        duration: '2-3 meses',
        color: '#5C3317',
        icon: '✨',
        objectives: [
            'Conseguir superficies lisas y uniformes en cualquier madera',
            'Aplicar aceites, barnices y lacas correctamente',
            'Entender qué acabado es el adecuado para cada uso',
            'Reparar imperfecciones antes del acabado',
        ],
        skills: [
            'Lijado progresivo profesional (80→120→180→220→320)',
            'Aplicación de aceite de tung / danish oil',
            'Barniz poliuretano al agua y al solvente',
            'Técnica de ceras de carnauba',
            'Relleno de nudos y poros',
            'Sellado y control de acabado final',
        ],
        exercises: [
            'Probar 4 acabados distintos en la misma madera → comparar',
            'Restaurar una pieza vieja de madera',
            'Construir una tabla de cocina con acabado de aceite',
            'Fotografiar cada pieza para portafolio',
        ],
        resources: [
            'Videos: comparativa de acabados para muebles',
            'Videos: técnica de lijado paso a paso',
            'Productos: Aceite de tung, barniz Sayerlack, cera Briwax',
        ],
    },
    {
        id: 4,
        title: 'Diseño Propio',
        subtitle: 'Sistemas modulares y estilo personal',
        duration: '4-6 meses',
        color: '#4A2912',
        icon: '📐',
        objectives: [
            'Desarrollar un estilo de diseño propio y reconocible',
            'Diseñar muebles desde cero en papel y software',
            'Crear sistemas de medidas propios y piezas modulares',
            'Calcular costos y materiales de un proyecto',
        ],
        skills: [
            'Diseño en papel: vistas, alzado, despiece',
            'SketchUp o Fusion 360 (básico) para diseño 3D',
            'Cálculo de cantidad de madera y desperdicio',
            'Proporciones áureas aplicadas a mueble',
            'Diseño para reparabilidad y desmontaje',
        ],
        exercises: [
            'Diseñar 3 variantes de la misma mesa',
            'Crear un sistema modular de estantería',
            'Desarrollar tu "mesa signature" con tu firma de diseño',
            'Documentar todos tus proyectos en portafolio físico y digital',
        ],
        resources: [
            'Videos: diseño y despiece de muebles en SketchUp',
            'Libros: "By Hand & Eye", "Furniture Design" de Jim Postell',
            'Inspiración: makers en Instagram y Pinterest',
        ],
    },
    {
        id: 5,
        title: 'Profesionalización',
        subtitle: 'Negocio, presencia y escala',
        duration: '6-12 meses',
        color: '#3D2208',
        icon: '💼',
        objectives: [
            'Cobrar tus primeras 3-5 piezas a precio justo',
            'Tener presencia en redes sociales con contenido de valor',
            'Entender costos, margen y precio de venta',
            'Desarrollar tu primer producto estrella de línea',
        ],
        skills: [
            'Cálculo de precio: materiales + tiempo + margen',
            'Fotografía de producto con celular',
            'Redes sociales: Instagram y TikTok para makers',
            'Trato con clientes: presupuesto, contrato, entrega',
            'Control de inventario y materiales',
        ],
        exercises: [
            'Vender tu primera pieza (aunque sea con amigo/familia)',
            'Publicar 12 posts de proceso en redes (1 mes)',
            'Calcular costo real de una mesa y fijar precio',
            'Contactar 3 diseñadores de interiores locales',
        ],
        resources: [
            'Podcast: "The Furniture Society", "Working Wood" ',
            'Videos: cómo vender muebles artesanales online',
            'Libro: "Building a Woodworking Business" (Tim Mannello)',
        ],
    },
]

export const MESA_ETERNA_STEPS = [
    {
        id: 1,
        title: 'Diseño y Planificación',
        icon: '📐',
        description: 'Definir medidas, estilo y materiales de la mesa',
        details: [
            'Definir uso: comedor, escritorio, exterior, café',
            'Medidas estándar: 75cm alto, 80-90cm ancho, largo a elegir',
            'Escoger tipo de tapa: maciza, tablero, mosaico de piezas',
            'Boceto en papel: vistas frontal, lateral, superior',
            'Lista de piezas: tapa, patas, travesaños, refuerzos',
        ],
        materials: [],
        tips: [
            'Grosor mínimo de tapa: 30-40mm para durabilidad real',
            'Patas mínimo 70x70mm para estabilidad sin tambaleo',
            'Diseñar para que sea desmontable si necesitás transportarla',
        ],
    },
    {
        id: 2,
        title: 'Selección de Madera',
        icon: '🌳',
        description: 'Elegir y comprar los materiales correctos',
        details: [
            'Para tapa: roble, fresno, guatambú, algarrobo o lenga (hardwoods)',
            'Para estructura: el mismo tipo o uno similar en dureza',
            'Verificar humedad de la madera (ideal 8-12% para interior)',
            'Comprar 15-20% más de lo calculado por desperdicio',
            'Revisar que las tablas estén planas y sin torcimientos',
        ],
        materials: [
            'Tablas para tapa: 40x150mm × largo + sobrante',
            'Patas: 70x70mm cuadradas o 60x80mm rectangulares',
            'Travesaños: 30x80mm',
            'Cola PVA para madera (tipo Titebond o similar)',
            'Tarugos o espigas de madera Ø8mm o Ø10mm',
            'Tornillos 4mm × 60mm y 4mm × 45mm',
            'Lija 80, 120, 180, 220, 320',
        ],
        tips: [
            'Evitar MDF o aglomerados — no son "eternos"',
            'Si el presupuesto es ajustado: pino pero en sección gruesa',
            'Dejar aclimatarse la madera 5-7 días en tu taller antes de cortar',
        ],
    },
    {
        id: 3,
        title: 'Corte y Preparación',
        icon: '🪚',
        description: 'Despiece y cortes precisos de todas las piezas',
        details: [
            'Hacer lista de corte (nombre de pieza, cantidad, medidas)',
            'Cortar piezas un 5mm más largas → ajustar después',
            'Cepillar o pasar por planeadora si hay alabeos',
            'Marcar con lápiz qué cara y canto son de referencia',
            'Escuadrar todas las piezas a medida final',
        ],
        materials: [],
        tips: [
            'Siempre medir dos veces, cortar una vez',
            'Usar una guía paralela fija — nunca a ojo con la sierra',
            'Numerar las piezas para no confundirlas',
        ],
    },
    {
        id: 4,
        title: 'Ensamble y Estructura',
        icon: '🔧',
        description: 'Unir todas las piezas de forma sólida',
        details: [
            'Hacer ensambles en seco primero (sin cola) para verificar todo',
            'Estructura bajo tapa: 2 travesaños laterales + 2 frontales',
            'Unir patas a travesaños con espigas y cola o tornillo + tarugo',
            'Verificar escuadra en diagonal antes de que seque la cola',
            'Fijar tapa con herrajes deslizantes (permite movimiento de la madera)',
            'Dejar secar 24hs bajo presión de sargentos',
        ],
        materials: [
            'Sargentos de apriete (mínimo 4)',
            'Escuadra de carpintero',
            'Cola PVA',
            'Tarugos de madera',
            'Tornillos y tacos',
        ],
        tips: [
            'La tapa maciza se mueve con la humedad: no pegarla rígidamente',
            'Usar herrajes en Z o "figure-8" para fijar tapa con movimiento',
            'Verificar que no tambalee en diagonal antes de encolar',
        ],
    },
    {
        id: 5,
        title: 'Lijado',
        icon: '✋',
        description: 'Progresión de lijado para superficie perfecta',
        details: [
            'Empezar con grano 80 si hay diferencias de nivel entre piezas',
            'Seguir con 120 → quitar todas las rayas del anterior',
            'Seguir con 180 → superficie comienza a abrir la veta',
            'Terminar con 220 o 320 según el acabado elegido',
            'Limpiar el polvo entre cada grano con trapo apenas húmedo',
            'Pasar un poco de agua, dejar secar y pasar 320 final (grain raising)',
        ],
        materials: [
            'Lija: grano 80, 120, 180, 220, 320',
            'Taco de lijar o lijadora orbital',
            'Aspiradora de polvo',
        ],
        tips: [
            'No saltar granos — si saltas del 80 al 180 quedan rayas',
            'Lijar siempre siguiendo la veta de la madera (no en círculos)',
            'Usar buena iluminación y luz rasante para ver imperfecciones',
        ],
    },
    {
        id: 6,
        title: 'Acabado Final',
        icon: '✨',
        description: 'Proteger y embellecer la madera para durar décadas',
        details: [
            'Limpiar toda la superficie de polvo y grasa (trapo con thinner)',
            'Primera mano de aceite de tung o danish oil → dejar 24hs',
            'Lijar suavemente con 400 y aplicar segunda mano',
            'Si elegís barniz: sellador + 2 manos de poliuretano al agua',
            'Pulir la última mano con lana de acero 0000 y cera de carnauba',
        ],
        materials: [
            'Aceite de tung puro o danish oil',
            'Barniz poliuretano al agua (opcional)',
            'Cera de carnauba',
            'Lana de acero 0000',
            'Pinceles de calidad',
            'Trapos de algodón sin pelusa',
        ],
        tips: [
            'El aceite de tung da el acabado más "eterno" y reparable con el tiempo',
            'Evitar barnices muy brillantes en mesas de uso diario',
            'Con aceite: reaplicar cada 1-2 años para mantener protección',
            'Poner felpa o gomas en las patas para no rayar el piso',
        ],
    },
]
